spring:
  application:
    name: dgap

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/dgap_db
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081